# Saving this here. Rofi color scheme. Made using this: https://skins.midnight-commander.org/
[skin]
truecolors=true
[lines]
    horiz = ─
    vert = │
    lefttop = ┌
    righttop = ┐
    leftbottom = └
    rightbottom = ┘
    topmiddle = ┬
    bottommiddle = ┴
    leftmiddle = ├
    rightmiddle = ┤
    cross = ┼
    dhoriz = ═
    dvert = ║
    dlefttop = ╔
    drighttop = ╗
    dleftbottom = ╚
    drightbottom = ╝
    dtopmiddle = ╤
    dbottommiddle = ╧
    dleftmiddle = ╟
    drightmiddle = ╢





[widget-panel]
    sort-up-char = ↑
    sort-down-char = ↓
    hiddenfiles-show-char = •
    hiddenfiles-hide-char = ○
    history-prev-item-char = «
    history-next-item-char = »
    history-show-list-char = ⇊
    filename-scroll-left-char = ❰
    filename-scroll-right-char = ❱

[widget-scrollbar]
    up-char = ▲
    down-char = ▼
    left-char = ◀
    right-char = ▶
    thumb-char = ■
    track-char = ▒

[widget-editor]
    window-state-char = ↕
    window-close-char = ✕
