--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kudlak/Pictures/Wallpaper/wallhaven-9oozpx.png"

-- Special
background="#040404"
foreground="#efcdc4"
cursor="#efcdc4"

-- Colors
color0="#040404"
color1="#3D66B8"
color2="#A3728C"
color3="#FC6A94"
color4="#389587"
color5="#3CA393"
color6="#4B9D99"
color7="#efcdc4"
color8="#a78f89"
color9="#3D66B8"
color10="#A3728C"
color11="#FC6A94"
color12="#389587"
color13="#3CA393"
color14="#4B9D99"
color15="#efcdc4"
