# Shell variables
# Generated by 'wal'
wallpaper='/home/kudlak/Pictures/Wallpaper/wallhaven-9oozpx.png'

# Special
background='#040404'
foreground='#efcdc4'
cursor='#efcdc4'

# Colors
color0='#040404'
color1='#3D66B8'
color2='#A3728C'
color3='#FC6A94'
color4='#389587'
color5='#3CA393'
color6='#4B9D99'
color7='#efcdc4'
color8='#a78f89'
color9='#3D66B8'
color10='#A3728C'
color11='#FC6A94'
color12='#389587'
color13='#3CA393'
color14='#4B9D99'
color15='#efcdc4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
